// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWHmJhPyHzZE0F8KIEdInOxpEooJD1X0',
    appId: '1:1023169656044:web:36420f7e9224f09ca621c9',
    messagingSenderId: '1023169656044',
    projectId: 'finalexam-c2695',
    authDomain: 'finalexam-c2695.firebaseapp.com',
    storageBucket: 'finalexam-c2695.appspot.com',
    measurementId: 'G-RPXFP30DNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL5KzKGSH_V-sH9labk7Ny2a6dS-0rHNg',
    appId: '1:1023169656044:android:1db34057b8dd5a51a621c9',
    messagingSenderId: '1023169656044',
    projectId: 'finalexam-c2695',
    storageBucket: 'finalexam-c2695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNJEtG1TQoT3Nb2bEtxaXKRqxiwb0kvw',
    appId: '1:1023169656044:ios:4b999267475905caa621c9',
    messagingSenderId: '1023169656044',
    projectId: 'finalexam-c2695',
    storageBucket: 'finalexam-c2695.appspot.com',
    iosBundleId: 'com.example.finalexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSNJEtG1TQoT3Nb2bEtxaXKRqxiwb0kvw',
    appId: '1:1023169656044:ios:4b999267475905caa621c9',
    messagingSenderId: '1023169656044',
    projectId: 'finalexam-c2695',
    storageBucket: 'finalexam-c2695.appspot.com',
    iosBundleId: 'com.example.finalexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWHmJhPyHzZE0F8KIEdInOxpEooJD1X0',
    appId: '1:1023169656044:web:ad7e645f817fe2eca621c9',
    messagingSenderId: '1023169656044',
    projectId: 'finalexam-c2695',
    authDomain: 'finalexam-c2695.firebaseapp.com',
    storageBucket: 'finalexam-c2695.appspot.com',
    measurementId: 'G-FYQZYE3TCJ',
  );
}
